### ISSUE TITLE
Error while reading from cache: System.IO.EndOfStreamException: Unable to read beyond the end of the stream.

### ISSUE THREAD

**Issue by ameetj85** [replaysMike/AnySerializer#12]
Hi Mike,
I am using v.1.1.8 of the library in which you have addressed the XMLDocument issue that I had brought up. I am now getting the following error anytime that I try to Deserialize data. If I use an older version of the library then the error does not occur.

System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.BinaryReader.ReadByte()
   at AnySerializer.TypeReader.ReadObject(BinaryReader reader, ExtendedType typeSupport, Int32 currentDepth, String path, UInt32& dataLength, UInt32& headerLength)
   at AnySerializer.TypeReader.ReadObjectType(Object newObj, BinaryReader reader, UInt32 length, ExtendedType typeSupport, Int32 currentDepth, String path, TypeDescriptor typeDescriptor)
   at AnySerializer.TypeReader.ReadObject(BinaryReader reader, ExtendedType typeSupport, Int32 currentDepth, String path, UInt32& dataLength, UInt32& headerLength)
   at AnySerializer.TypeReader.ReadObject(BinaryReader reader, ExtendedType typeSupport, Int32 currentDepth, String path, UInt32& dataLength, UInt32& headerLength)
   at AnySerializer.TypeReader.Read(BinaryReader reader, ExtendedType typeSupport, UInt32 maxDepth, SerializerOptions options, ICollection`1 ignoreAttributes, TypeRegistry typeRegistry, ICollection`1 ignorePropertiesOrPaths)
   at AnySerializer.DeserializerInternal.InspectAndDeserialize(Type type, Byte[] sourceBytes, UInt32 maxDepth, SerializerOptions options, ICollection`1 ignoreAttributes, TypeRegistry typeRegistry, ICollection`1 ignorePropertiesOrPaths)
   at AnySerializer.DeserializerInternal.InspectAndDeserialize[T](Byte[] sourceBytes, UInt32 maxDepth, SerializerOptions options, ICollection`1 ignoreAttributes, TypeRegistry typeRegistry, ICollection`1 ignorePropertiesOrPaths)
   at AnySerializer.SerializerProvider.Deserialize[T](Byte[] bytes, SerializerOptions options)

**Comment by replaysMike** [comment]
I completely missed this ticket and will address this issue, apologies for the long delay
